### PR TITLE
Stop leaking user data lol

### PR DESCRIPTION
**Pull request by 3nt3**
This fixes two vulnerabilities:
- unauthorized access to `GET /user/:id`
- ability to register using emails that look like `john.doe@example.com@gymhaan.de` and them being delivered to `john.doe@example.com` which kind of makes all the email validation pointless

Thanks to @Zischknall for reporting both

### CODE REVIEW

**Comment by durek1337** [comment]
Thanks! It's now applied on the server.

**Comment by NoobTracker** [comment]
Hey, I was about to try out the `john.doe@example.com@gymhaan.de` trick when I realised that the mail validation is client side only :D 
(did you watch fasterthanli.me's [The Yellow Room](https://youtu.be/xh2tYivkSNM)?)

**Comment by 3nt3** [comment]
uhhhhm am I missing something here?

This is the email validation code.

```ts
  // necessary because nodemailer will otherwise send asdf@foo.com@gymhaan.de
  // to asdf@foo.com and that circumvents the whole "only gymhaan email addresses
  // are valid" thing
  const emailSplitByAt = email.split('@');
  const removedAllButFirstAt = emailSplitByAt[0] + emailSplitByAt.slice(1, emailSplitByAt.length).join('').replace('@', '');

  // hackery because frontend
  if (!checkEmailValidity(removedAllButFirstAt) && !checkEmailValidity(removedAllButFirstAt + "@gymhaan.de"))
    return res.status(400).json({ msg: "invalid email" });
 ```

And `checkEmailValidity` is defined as

```ts
const checkEmailValidity = (email: string): boolean => {
  return /(.*)\.(.*)@gymhaan.de/.test(email);
};
```

**Comment by NoobTracker** [comment]
Wait, you're doing server side verification of sorts - why on earth is ther [looks at code] hahaha I have a hypothesis: when it tries to validate an email, it also passes `removedAllButFirstAt + "@gymhaan.de"` to the verification function, so it is considered okay! Also I did not expect a response at 4 am ngl ^^

**Comment by 3nt3** [comment]
It accepts it -- but removes all `@` signs after the first one. So the verification email shouldn't be able to actually be sent since it would be `john.doe@example.com@gymhaan.de -> john.doe@example.comgymhaan.de`, if my thinking is correct here

**Comment by NoobTracker** [comment]
Hmmm, idk. Just try it tho, use some throwaway mail address, put it into your form, use element inspect to disable the `disable`, ???, Profit!

**Comment by NoobTracker** [comment]
> It accepts it -- but removes all `@` signs after the first one. So the verification email shouldn't be able to actually be sent since it would be `john.doe@example.com@gymhaan.de -> john.doe@example.comgymhaan.de`, if my thinking is correct here

No, here's the relevant code:
```ts
  if (!checkEmailValidity(removedAllButFirstAt) && !checkEmailValidity(removedAllButFirstAt + "@gymhaan.de"))
    return res.status(400).json({ msg: "invalid email" });
```
It checks whether the sanetised mail address is valid with or without an extra "@gymhaan.de", then proceeds to forget if it needs to add "@gymhaan.de" or not ...

**Comment by 3nt3** [comment]
lmao how did I miss that and how did that even remotely work when I coded it up lol

**Comment by NoobTracker** [comment]
It is pretty funny tho :)
(and it's managed to keep me awake for way too long aaaah)

**Comment by NoobTracker** [comment]
> It accepts it -- but removes all `@` signs after the first one. So the verification email shouldn't be able to actually be sent since it would be `john.doe@example.com@gymhaan.de -> john.doe@example.comgymhaan.de`, if my thinking is correct here

Oh, and by the way, that would've been not that great either, I could've just bought the domain comgymhaan.de, set up an `example` subdomain and receive the mail ... if I had money, that is.

**Pull request merged**
